export const PROMPT_VOCABULARY = {
	i: {
		kanji: "私",
		kana: "わたし",
		type: "noun",
		difficulty: "easy",
		roles: ["subject"],
		english: { subject: "I", object: "me" },
		thirdPersonSingular: false,
	},
	he: {
		kanji: "彼",
		kana: "かれ",
		type: "noun",
		difficulty: "easy",
		roles: ["subject", "patient"],
		english: { subject: "he", object: "him" },
		thirdPersonSingular: true,
	},
	she: {
		kanji: "彼女",
		kana: "かのじょ",
		type: "noun",
		difficulty: "easy",
		roles: ["subject", "patient"],
		english: { subject: "she", object: "her" },
		thirdPersonSingular: true,
	},
	teacher: {
		kanji: "先生",
		kana: "せんせい",
		type: "noun",
		difficulty: "easy",
		roles: ["subject", "agent", "companion"],
		english: { subject: "the teacher", object: "the teacher" },
		thirdPersonSingular: true,
	},
	student: {
		kanji: "学生",
		kana: "がくせい",
		type: "noun",
		difficulty: "medium",
		roles: ["subject", "patient", "agent", "companion"],
		english: { subject: "the student", object: "the student" },
		thirdPersonSingular: true,
	},
	friend: {
		kanji: "友達",
		kana: "ともだち",
		type: "noun",
		difficulty: "medium",
		roles: ["subject", "patient", "agent", "companion"],
		english: { subject: "my friend", object: "my friend" },
		thirdPersonSingular: true,
	},
	mother: {
		kanji: "母",
		kana: "はは",
		type: "noun",
		difficulty: "medium",
		roles: ["subject"],
		english: { subject: "my mother", object: "my mother" },
		thirdPersonSingular: true,
	},
	father: {
		kanji: "父",
		kana: "ちち",
		type: "noun",
		difficulty: "medium",
		roles: ["subject"],
		english: { subject: "my father", object: "my father" },
		thirdPersonSingular: true,
	},
	child: {
		kanji: "子供",
		kana: "こども",
		type: "noun",
		difficulty: "medium",
		roles: ["subject"],
		english: { subject: "the child", object: "the child" },
		thirdPersonSingular: true,
	},
	doctor: {
		kanji: "医者",
		kana: "いしゃ",
		type: "noun",
		difficulty: "medium",
		roles: ["subject"],
		english: { subject: "the doctor", object: "the doctor" },
		thirdPersonSingular: true,
	},
	school: {
		kanji: "学校",
		kana: "がっこう",
		type: "noun",
		difficulty: "easy",
		roles: ["place", "destination"],
		english: { place: "at school", destination: "to school" },
	},
	station: {
		kanji: "駅",
		kana: "えき",
		type: "noun",
		difficulty: "easy",
		roles: ["place", "destination"],
		english: { place: "at the station", destination: "to the station" },
	},
	library: {
		kanji: "図書館",
		kana: "としょかん",
		type: "noun",
		difficulty: "easy",
		roles: ["place", "destination"],
		english: { subject: "the library", place: "at the library", destination: "to the library" },
	},
	home: {
		kanji: "家",
		kana: "いえ",
		type: "noun",
		difficulty: "easy",
		roles: ["place", "destination"],
		english: { place: "at home", destination: "home" },
	},
	room: {
		kanji: "部屋",
		kana: "へや",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { subject: "the room", place: "in the room", destination: "to the room" },
	},
	store: {
		kanji: "店",
		kana: "みせ",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the store", destination: "to the store" },
	},
	park: {
		kanji: "公園",
		kana: "こうえん",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the park", destination: "to the park" },
	},
	company: {
		kanji: "会社",
		kana: "かいしゃ",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the company", destination: "to the company" },
	},
	hospital: {
		kanji: "病院",
		kana: "びょういん",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the hospital", destination: "to the hospital" },
	},
	restaurant: {
		kanji: "レストラン",
		kana: "レストラン",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: {
			subject: "the restaurant",
			place: "at the restaurant",
			destination: "to the restaurant",
		},
	},
	classroom: {
		kanji: "教室",
		kana: "きょうしつ",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: {
			subject: "the classroom",
			place: "in the classroom",
			destination: "to the classroom",
		},
	},
	office: {
		kanji: "事務所",
		kana: "じむしょ",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { subject: "the office", place: "at the office", destination: "to the office" },
	},
	supermarket: {
		kanji: "スーパー",
		kana: "スーパー",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: {
			subject: "the supermarket",
			place: "at the supermarket",
			destination: "to the supermarket",
		},
	},
	movieTheater: {
		kanji: "映画館",
		kana: "えいがかん",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the movie theater", destination: "to the movie theater" },
	},
	rain: {
		kanji: "雨",
		kana: "あめ",
		type: "noun",
		difficulty: "easy",
		roles: ["weather"],
		english: { subject: "it" },
		thirdPersonSingular: true,
	},
	book: {
		kanji: "本",
		kana: "ほん",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { subject: "the book", object: "a book", plural: "books" },
	},
	sushi: {
		kanji: "寿司",
		kana: "すし",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { object: "sushi" },
	},
	water: {
		kanji: "水",
		kana: "みず",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { object: "water" },
	},
	japanese: {
		kanji: "日本語",
		kana: "にほんご",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { object: "Japanese" },
	},
	movie: {
		kanji: "映画",
		kana: "えいが",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { subject: "the movie", object: "a movie", plural: "movies" },
	},
	letter: {
		kanji: "手紙",
		kana: "てがみ",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { subject: "the letter", object: "a letter", plural: "letters" },
	},
	newspaper: {
		kanji: "新聞",
		kana: "しんぶん",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { subject: "the newspaper", object: "the newspaper", plural: "newspapers" },
	},
	rice: {
		kanji: "ご飯",
		kana: "ごはん",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { object: "rice" },
	},
	tea: {
		kanji: "お茶",
		kana: "おちゃ",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { object: "tea" },
	},
	coffee: {
		kanji: "コーヒー",
		kana: "コーヒー",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { object: "coffee" },
	},
	lunch: {
		kanji: "昼ご飯",
		kana: "ひるごはん",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { object: "lunch" },
	},
	homework: {
		kanji: "宿題",
		kana: "しゅくだい",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { subject: "the homework", object: "homework", plural: "homework" },
	},
	phone: {
		kanji: "電話",
		kana: "でんわ",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { subject: "the phone", object: "a phone", plural: "phones" },
	},
	music: {
		kanji: "音楽",
		kana: "おんがく",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { object: "music" },
	},
	new: {
		kanji: "新しい",
		kana: "あたらしい",
		type: "adjective",
		difficulty: "easy",
		roles: ["adjective"],
		english: { predicate: "new" },
	},
	old: {
		kanji: "古い",
		kana: "ふるい",
		type: "adjective",
		difficulty: "easy",
		roles: ["adjective"],
		english: { predicate: "old" },
	},
	big: {
		kanji: "大きい",
		kana: "おおきい",
		type: "adjective",
		difficulty: "medium",
		roles: ["adjective"],
		english: { predicate: "big" },
	},
	small: {
		kanji: "小さい",
		kana: "ちいさい",
		type: "adjective",
		difficulty: "medium",
		roles: ["adjective"],
		english: { predicate: "small" },
	},
	quiet: {
		kanji: "静か",
		kana: "しずか",
		type: "adjective",
		difficulty: "medium",
		roles: ["adjective"],
		english: { predicate: "quiet" },
	},
	simple: {
		kanji: "簡単",
		kana: "かんたん",
		type: "adjective",
		difficulty: "medium",
		roles: ["adjective"],
		english: { predicate: "simple" },
	},
	difficult: {
		kanji: "難しい",
		kana: "むずかしい",
		type: "adjective",
		difficulty: "medium",
		roles: ["adjective"],
		english: { predicate: "difficult" },
	},
	fun: {
		kanji: "楽しい",
		kana: "たのしい",
		type: "adjective",
		difficulty: "medium",
		roles: ["adjective"],
		english: { predicate: "fun" },
	},
	important: {
		kanji: "大切",
		kana: "たいせつ",
		type: "adjective",
		difficulty: "medium",
		roles: ["adjective"],
		english: { predicate: "important" },
	},
	expensive: {
		kanji: "高い",
		kana: "たかい",
		type: "adjective",
		difficulty: "medium",
		roles: ["adjective"],
		english: { predicate: "expensive" },
	},
	cheap: {
		kanji: "安い",
		kana: "やすい",
		type: "adjective",
		difficulty: "medium",
		roles: ["adjective"],
		english: { predicate: "cheap" },
	},
	quickly: {
		kanji: "早く",
		kana: "はやく",
		type: "adverb",
		difficulty: "medium",
		roles: ["adverb"],
		english: { adverb: "quickly" },
	},
	slowly: {
		kanji: "ゆっくり",
		kana: "ゆっくり",
		type: "adverb",
		difficulty: "medium",
		roles: ["adverb"],
		english: { adverb: "slowly" },
	},
	well: {
		kanji: "よく",
		kana: "よく",
		type: "adverb",
		difficulty: "medium",
		roles: ["adverb"],
		english: { adverb: "well" },
	},
	sometimes: {
		kanji: "時々",
		kana: "ときどき",
		type: "adverb",
		difficulty: "medium",
		roles: ["adverb"],
		english: { adverb: "sometimes" },
	},
	today: {
		kanji: "今日",
		kana: "きょう",
		type: "adverb",
		difficulty: "medium",
		roles: ["adverb"],
		english: { adverb: "today" },
	},
	yesterday: {
		kanji: "昨日",
		kana: "きのう",
		type: "adverb",
		difficulty: "medium",
		roles: ["adverb"],
		english: { adverb: "yesterday" },
	},
	tomorrow: {
		kanji: "明日",
		kana: "あした",
		type: "adverb",
		difficulty: "medium",
		roles: ["adverb"],
		english: { adverb: "tomorrow" },
	},
	often: {
		kanji: "よく",
		kana: "よく",
		type: "adverb",
		difficulty: "medium",
		roles: ["adverb"],
		english: { adverb: "often" },
	},
	usually: {
		kanji: "普通",
		kana: "ふつう",
		type: "adverb",
		difficulty: "medium",
		roles: ["adverb"],
		english: { adverb: "usually" },
	},
	bookCounter: {
		kanji: "冊",
		kana: "冊",
		type: "counter",
		difficulty: "medium",
		roles: ["counter"],
		english: { counter: "books" },
	},
	generalCounter: {
		kanji: "個",
		kana: "個",
		type: "counter",
		difficulty: "medium",
		roles: ["counter"],
		english: { counter: "things" },
	},
	flatCounter: {
		kanji: "枚",
		kana: "枚",
		type: "counter",
		difficulty: "medium",
		roles: ["counter"],
		english: { counter: "flat things" },
	},
	go: {
		kanji: "いく",
		kana: "いく",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "go", present3: "goes", past: "went" },
	},
	come: {
		kanji: "くる",
		kana: "くる",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "come", present3: "comes", past: "came" },
	},
	eat: {
		kanji: "食べる",
		kana: "たべる",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "eat", present3: "eats", past: "ate" },
	},
	drink: {
		kanji: "飲む",
		kana: "のむ",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "drink", present3: "drinks", past: "drank" },
	},
	read: {
		kanji: "読む",
		kana: "よむ",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "read", present3: "reads", past: "read" },
	},
	buy: {
		kanji: "買う",
		kana: "かう",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "buy", present3: "buys", past: "bought" },
	},
	study: {
		kanji: "勉強する",
		kana: "べんきょうする",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "study", present3: "studies", past: "studied" },
	},
	watch: {
		kanji: "みる",
		kana: "みる",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "watch", present3: "watches", past: "watched" },
	},
	write: {
		kanji: "書く",
		kana: "かく",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "write", present3: "writes", past: "wrote" },
	},
	speak: {
		kanji: "話す",
		kana: "はなす",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "speak", present3: "speaks", past: "spoke" },
	},
	listen: {
		kanji: "聞く",
		kana: "きく",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "listen to", present3: "listens to", past: "listened to" },
	},
	wait: {
		kanji: "待つ",
		kana: "まつ",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "wait", present3: "waits", past: "waited" },
	},
	use: {
		kanji: "使う",
		kana: "つかう",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "use", present3: "uses", past: "used" },
	},
	make: {
		kanji: "作る",
		kana: "つくる",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "make", present3: "makes", past: "made" },
	},
	praise: {
		kanji: "褒める",
		kana: "ほめる",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "praise", present3: "praises", past: "praised" },
	},
	fall: {
		kanji: "降る",
		kana: "ふる",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "rain", present3: "rains", past: "rained" },
	},
}

export function getPromptVocabularyEntry(key) {
	const vocabularyEntry = PROMPT_VOCABULARY[key]
	if (!vocabularyEntry) throw new Error(`Unknown prompt vocabulary key: ${key}`)

	return vocabularyEntry
}
